### ISSUE TITLE
Question: Is that safe to remove symbols from DefaultABC?

### ISSUE THREAD

**Issue by sgon00** [teris-io/shortid#10]
Is that safe to remove symbols from `DefaultABC`?
Basically, use the string `"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"` instead.
I am using it to generate shorten URL and do not wish to see symbols from the URL.
Thanks a lot for your project.

## Edited:

Sorry that I didn't try it before asking this question. I tried to remove those two symbols and return error message `panic: alphabet must contain 64 unique characters`. I think that means I can NOT remove symbols. It will be nice I can remove symbols from URL. The id does not have to be 100% unique. I will check the id existence before insert and re-generate if it exists.

**Comment by osklyar** [comment]
No, you cannot remove symbols from the default set. You can provide your own, but as it says `alphabet must contain 64 unique characters`, which means you can use other symbols, but this set was selected to be URL friendly.
