### ISSUE TITLE
worker id problem

### ISSUE THREAD

**Issue by jinze** [teris-io/shortid#2]
when I deploy my application in a docker cluster (k8s or docker-compose), I have no method to assign a worker id for different container, I can only get an docker container ID in my app by $HOSTNAME.I want to know what is the best practice to use the lib or generate an shortid by myself?

**Comment by osklyar** [comment]
I do not quite see how this is an issue of the library. There are dozens of mechanisms how you could define a unique worker Id value per container. You could have an environment variable, you could have a centralised service that you ask for an Id based on a rotating basis, you could have a fixed mapping of hostnames to worker Ids shared among all instances via a volume or a service. Anything will work fully independent of the shortid library.
