### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by danteay** [teris-io/shortid#4]
Hey Guys, I have a gin project actualy using this library, but sometimes send a panic error when generate a new SortID.

This is the error:
![captura de pantalla de 2017-03-25 21-19-53](https://cloud.githubusercontent.com/assets/9085902/24328218/55c2ef04-11a9-11e7-97ac-b055f6e28849.png)

An this is my generation code:
```go
sid, _ := shortid.New(1, shortid.DefaultABC, 2342)
ssid,e1 := sid.Generate()
```
What is the reason of this error?

**Comment by osklyar** [comment]
At the moment I do not see any obvious error given also that there is a test that generates millions of entries within the shortest possible period. Could you please add a panic recovery to the method generating the "index out of bounds" and print out all the variables involved in the index computation. If the error occurs again I would have more chances to understand the cause of the problem.

**Comment by shi-yang** [comment]
Hi. I also have the same issue.

I changed these lines of code:

https://github.com/teris-io/shortid/blob/771a37caa5cf0c81f585d7b6df4dfc77e0615b5c/shortid.go#L322-L326

to:

```golang
	fmt.Println(res)
	for i := range res {
		shift := digits * uint(i)
		index := (int(val>>shift) & mask) | random[i]
		fmt.Printf("val: %d   shift: %d   int(val>>shift): %d\n", val, shift, int(val>>shift))
		fmt.Printf("mask:%d   (int(val>>shift) & mask):%d   random[i]:%d\n", mask, int(val>>shift) & mask, random[i])
		fmt.Printf("shift: %d  index: %d\n", shift, index)
		fmt.Printf("abc.alphabet len: %d\n", len(abc.alphabet))
		res[i] = abc.alphabet[index]
	}
```

and the output result:
```
[0 0 0 0 0 0 0 0]
val: 112408516568   shift: 0   int(val>>shift): 112408516568
mask:31   (int(val>>shift) & mask):24   random[i]:32
shift: 0  index: 56
abc.alphabet len: 62
val: 112408516568   shift: 5   int(val>>shift): 3512766142
mask:31   (int(val>>shift) & mask):30   random[i]:32
shift: 5  index: 62
abc.alphabet len: 62
Recovered: runtime error: index out of range
```

**Comment by osklyar** [comment]
Would you be willing to rootcause and submit a pull request to fix it?

**Comment by shi-yang** [comment]
Sorry, it is my mistake. In my project I modified the value of `DefaultABC`(Reduced number of its characters) and caused the issue.
When I restore to its original value, this problem can not be reproduced. 
Now everything works fine.

**Comment by asad-awadia** [comment]
Same for me - I modified the value of Default abc because I only want lowercase alphanumeric

maybe it is worth opening up a function to modify it

**Comment by asad-awadia** [comment]
this thing needs 64 unique characters-I just want to use lowercase alphabets

**Comment by asad-awadia** [comment]
@osklyar

**Comment by osklyar** [comment]
The algo works for an abc of 64 unique characters. They can be anything, but it will fail if it is shorter than 64 and it will generate non-unique IDs if it is contains repetitions. There is nothing that can be done within this library for that. You can fork it, however, and change the algorithm to operate on a different abc. Expect, however, that your IDs will be longer if you reduce the size of the abc.
