### ISSUE TITLE
Returning an error

### ISSUE THREAD

**Issue by herkyl** [teris-io/shortid#5]
First of all really good job creating this library! Coming from Node.js I was searching for a shortid alternative a year ago, you finally created it!

When can I expect this library to return an error?
Could this happen randomly, should I panic at this point? Or will this only happen during the first `Generate()` call?

I'm asking because my current ID generation module does not return an error and I'd prefer to keep my code this way.

**Comment by osklyar** [comment]
Generally, it should not return any errors as the only source are alphabet-based encoding and those are mostly hypothetical rather than real.
